ARG COMPOSE_PROJECT_NAME
FROM registry.gitlab.com/flagstudio/${COMPOSE_PROJECT_NAME}:base

# Add a non-root user to prevent files being created with root permissions on host machine.
ARG PUID=1000
ENV PUID ${PUID}
ARG PGID=1000
ENV PGID ${PGID}

RUN groupadd -g ${PGID} local && \
    useradd -u ${PUID} -g local -m local -G local && \
    usermod -p "*" local

###########################################################################
# Configs
###########################################################################


COPY ./docker/app/laraflag.ini /usr/local/etc/php/conf.d
COPY ./docker/app/www.conf /usr/local/etc/php-fpm.d/www.conf
COPY ./docker/app/supervisord_build.conf /etc/supervisord.conf
COPY ./docker/app/Caddyfile /etc/Caddyfile
#COPY ./docker/app/crontab /var/spool/cron/crontabs/root
#RUN crontab /var/spool/cron/crontabs/root

###########################################################################
# Opcache:
###########################################################################

ARG PHP_FPM_INSTALL_OPCACHE=true

RUN if [ ${PHP_FPM_INSTALL_OPCACHE} = true ]; then \
    docker-php-ext-install opcache \
;fi

# Copy opcache configration
COPY ./docker/app/opcache.ini /usr/local/etc/php/conf.d/opcache.ini

###########################################################################
# Copy code
###########################################################################

USER www-data:www-data
COPY . /var/www/

###########################################################################
# Composer packages
###########################################################################

WORKDIR /var/www
USER root

RUN composer install --optimize-autoloader --no-scripts -q
RUN composer dumpautoload

###########################################################################
# NPM
###########################################################################

RUN npm i
RUN npm run prod

###########################################################################
# Prepare Laravel for Prod
###########################################################################

RUN php artisan package:discover
RUN php artisan storage:link
RUN php artisan scribe:generate
RUN php artisan optimize

# Micro Editor https://micro-editor.github.io/
RUN curl https://getmic.ro | bash; \
        mv micro /root/micro; \
        echo 'alias m="~/micro"' >> /root/.bashrc

CMD ["/usr/bin/supervisord", "-n", "-c",  "/etc/supervisord.conf"]

EXPOSE 8080
