# This is app image build in GitLab CI
ARG IMAGE_REGISTRY_PATH=registry.gitlab.com/flagstudio
ARG REPOSITORY_NAME

FROM ${IMAGE_REGISTRY_PATH}/${REPOSITORY_NAME}:base

# Start as root
USER root

###########################################################################
# Configs
###########################################################################

COPY ./docker/app/laraflag.ini /usr/local/etc/php/conf.d
COPY ./docker/app/www.conf /usr/local/etc/php-fpm.d/www.conf
COPY ./docker/app/supervisord.conf /etc/supervisord.conf
COPY ./docker/app/crontab /var/spool/cron/crontabs/root
RUN crontab /var/spool/cron/crontabs/root

###########################################################################
# Copy code
###########################################################################

USER flag
COPY . /home/flag/www
WORKDIR /home/flag/www

USER root
RUN echo "" >> ~/.bashrc \
    && echo 'export PATH="~/.composer/vendor/bin:$PATH"' >> ~/.bashrc \
    && mkdir -p /home/flag/www/storage/app/public \
    /home/flag/www/storage/framework/views \
    /home/flag/www/storage/framework/sessions \
    /home/flag/www/storage/framework/cache/data \
    /home/flag/www/storage/logs \
    && rm -Rf /var/www/bootstrap/cache/**

RUN chown -R flag:flag /home/flag/www \
    && chmod -R 0777 /home/flag/www/storage /home/flag/www/bootstrap

###########################################################################
# Laravel Nova
###########################################################################
# Nova CMS credentials
ARG INSTALL_NOVA=true
ARG NOVA_USERNAME
ARG NOVA_PASSWORD
ENV NOVA_USERNAME=$NOVA_USERNAME
ENV NOVA_PASSWORD=$NOVA_PASSWORD

USER flag

RUN if [ ${INSTALL_NOVA} = true ]; then \
    composer global config http-basic.nova.laravel.com ${NOVA_USERNAME} ${NOVA_PASSWORD} \
    && echo "NOVA CREDENTIALS ARE SETS" \
;fi

###########################################################################
# Composer packages
###########################################################################

ARG WITH_DEV=false

ARG WITH_DEV=false

RUN if [ ${WITH_DEV} = true ] ; then composer install --optimize-autoloader ; else composer install --optimize-autoloader --no-dev --no-scripts ; fi
RUN composer dumpautoload

###########################################################################
# NPM
###########################################################################

RUN npm ci \
    && npm run prod \
    && npm cache clean --force \
    && rm -rf node_modules/

###########################################################################
# Prepare Laravel for Prod
###########################################################################

RUN php artisan package:discover \
    && php artisan storage:link \
    && php artisan route:cache

USER root

CMD ["sh", "-c", "/usr/bin/supervisord -n -c /etc/supervisord.conf ; su - flag ;"]

EXPOSE 8888 9000


