# This is app image build for local development
ARG IMAGE_REGISTRY_PATH=registry.gitlab.com
ARG REPOSITORY_NAME

FROM ${IMAGE_REGISTRY_PATH}/${REPOSITORY_NAME}:base

# Start as root
USER root

###########################################################################
# Configs
###########################################################################

COPY ./docker/app/laraflag.ini /usr/local/etc/php/conf.d
COPY ./docker/app/www.conf /usr/local/etc/php-fpm.d/www.conf
COPY ./docker/app/supervisord.conf /etc/supervisord.conf
COPY ./docker/app/crontab /var/spool/cron/crontabs/root
COPY ./docker/app/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini
RUN crontab /var/spool/cron/crontabs/root

USER flag

WORKDIR /home/flag/www

ARG INSTALL_NOVA=true
ENV INSTALL_NOVA=$INSTALL_NOVA
RUN if [ ${INSTALL_NOVA} = true ]; then \
    composer global config http-basic.nova.laravel.com ${NOVA_USERNAME} ${NOVA_PASSWORD} \
    && echo "NOVA CREDENTIALS ARE SETS" \
;fi

USER root

RUN pecl install xdebug-3.1.3 \
    && docker-php-ext-enable xdebug

CMD ["/usr/bin/supervisord", "-n", "-c",  "/etc/supervisord.conf"]

EXPOSE 8888 9000


