version: '3.5'

services:
  ### Just builds app image like in CI but doing it locally ##############################################
  # docker-compose --env-file ./.env.test -f docker-compose.build-app.yml build
  base:
    container_name: ${COMPOSE_PROJECT_NAME}_app_${APP_IMAGE_TAG}
    build:
      args:
        - IMAGE_REGISTRY_PATH=${IMAGE_REGISTRY_PATH}
        - REPOSITORY_NAME=${REPOSITORY_NAME}
        - NOVA_USERNAME=${NOVA_USERNAME}
        - NOVA_PASSWORD=${NOVA_PASSWORD}
        - INSTALL_NOVA=${INSTALL_NOVA:-true}
      context: .
      dockerfile: docker/app/Dockerfile_app_build
    image: ${IMAGE_REGISTRY_PATH}/${REPOSITORY_NAME}:${APP_IMAGE_TAG}
